export interface ProjectData {
  slug: string
  title: string
  sector: string
  date: string
  hero: string
  lead: string
  client: string
  location: string
  product: string
  features: string[]
  quote: string
  quoteAttr: string
  gallery: string[]
}

export const PROJECTS_DATA: Record<string, ProjectData> = {
  'case-study-1': {
    slug: 'case-study-1',
    title: 'Seah Wind — UK\'s Largest Offshore Wind Farm',
    sector: 'Renewable Energy',
    date: '',
    hero: '/media/windfarm.png',
    lead: 'Todd Engineering delivered a specialist large-scale coating and refinishing facility supporting the UK\'s largest offshore wind farm project — demonstrating capability far beyond automotive into heavy industrial and renewable energy sectors.',
    client: 'Seah Wind',
    location: 'United Kingdom',
    product: '',
    features: [],
    quote: '',
    quoteAttr: '',
    gallery: [],
  },
  'case-study-2': {
    slug: 'case-study-2',
    title: 'Dubai Aerospace Facility',
    sector: 'Aerospace',
    date: '',
    hero: '/media/aerospace.png',
    lead: 'Todd Engineering specified and delivered a high-specification aerospace coating facility in Dubai — meeting the exacting environmental and finish quality standards demanded by the aviation industry.',
    client: '',
    location: 'Dubai, UAE',
    product: '',
    features: [],
    quote: '',
    quoteAttr: '',
    gallery: [],
  },
  'case-study-3': {
    slug: 'case-study-3',
    title: 'Amalgam — Specialist Refinishing Facility',
    sector: 'Automotive',
    date: '',
    hero: '/media/about-todd.jpg',
    lead: 'Amalgam approached Todd Engineering to create a specialist refinishing facility capable of handling high-value collectible and competition vehicles to the highest standard of finish.',
    client: 'Amalgam',
    location: '',
    product: '',
    features: [],
    quote: '',
    quoteAttr: '',
    gallery: [],
  },
  'sandal-bmw': {
    slug: 'sandal-bmw',
    title: 'Sandal BMW — Poseidon Dual Installation',
    sector: 'Automotive',
    date: 'July 2024',
    hero: 'https://www.toddengineering.co.uk/media/o5bdbnbj/img_3891.png',
    lead: 'Sandal BMW & Mini, a long-standing Todd Engineering customer, enhanced their bodyshop with a dual Poseidon installation alongside a new BMW Colour System. The project was meticulously planned to maintain full operational continuity throughout — Sandal BMW never stopped trading during the upgrade.',
    client: 'Sandal BMW & Mini',
    location: '',
    product: '',
    features: [
      '2× Poseidon Spray Booths — Low-profile full downdraught systems with Eco+ energy-saving mode. Hydracure technology for water-based curing efficiency.',
      'Bespoke Paint Mixing Room — Equipped with shelving, cupboards and an extraction bench for optimal functionality and colour accuracy.',
      'Gun Wash Room — Dedicated separate facility for efficient equipment maintenance.',
      'BMW Colour System — Professional factory-quality refinishing across all BMW and MINI products, integrated alongside the new booths.',
      'Zero-Downtime Installation — Meticulously planned phased installation maintained full bodyshop operations throughout.',
    ],
    quote: 'Huge thanks to Todd Engineering. You\'ve done an amazing job! The booths are fantastic, and the installation couldn\'t have gone smoother. We changed paint schemes and underwent training, all while staying operational.',
    quoteAttr: 'Reuben Abbott, Bodyshop Manager — Sandal BMW',
    gallery: [
      'https://www.toddengineering.co.uk/media/i4clurxo/img_3873.png',
      'https://www.toddengineering.co.uk/media/wkjge0l3/img_3733.png',
      'https://www.toddengineering.co.uk/media/wjhh4sd2/2.jpg',
      'https://www.toddengineering.co.uk/media/3j5ffgvv/3.jpg',
      'https://www.toddengineering.co.uk/media/2k2iaqhf/1.jpg',
    ],
  },
  'smallest-cog': {
    slug: 'smallest-cog',
    title: 'The Smallest COG — Richard Hammond\'s Workshop',
    sector: 'Automotive',
    date: 'March 2024',
    hero: 'https://www.toddengineering.co.uk/media/3emjgs10/eob_2047eob.jpg',
    lead: 'The Smallest COG, owned by presenter Richard Hammond, is a Cotswolds workshop dedicated to restoring and refinishing iconic vehicles with exceptional precision. Todd Engineering delivered a compact but fully professional refinishing setup — demonstrating that even in space-constrained environments, uncompromising quality is achievable.',
    client: 'The Smallest COG',
    location: 'Cotswolds, UK',
    product: '',
    features: [
      'Poseidon Spray Booth — Full downdraught extraction ensuring a pristine, dust-free environment for flawless restoration finishes. Eco+ energy-saving modes reducing operational costs.',
      'Hades Preparation Room — Advanced airflow and extraction for clean preparation work, seamlessly connected to the spray booth for smooth workflow transitions.',
      'Paint Mixing Room — Centralised controls for accurate colour matching — essential for high-value classic and luxury vehicle restorations.',
      'Compressor System — High-performance air supply delivering consistent, reliable performance across all refinishing processes.',
    ],
    quote: '',
    quoteAttr: '',
    gallery: [
      'https://www.toddengineering.co.uk/media/hb5g3snn/242243184_128913126142669_7541811579568133041_n.jpg',
      'https://www.toddengineering.co.uk/media/0g5ddy1p/242194729_128913152809333_9144103536313955115_n.jpg',
      'https://www.toddengineering.co.uk/media/f4matamf/457495509_523675116702953_6152066328697082405_n.jpg',
      'https://www.toddengineering.co.uk/media/rjlpvj2o/img_4619.png',
      'https://www.toddengineering.co.uk/media/ie3prqf2/img_1967.png',
    ],
  },
  'hills-helicopters': {
    slug: 'hills-helicopters',
    title: 'Hills Helicopters — HX50 Production Facility',
    sector: 'Aerospace',
    date: 'October 2024',
    hero: 'https://www.toddengineering.co.uk/media/tqqcixtw/img_4588.jpg',
    lead: 'Hills Helicopters, a leader in bespoke helicopter design and manufacturing, partnered with Todd Engineering to equip their new purpose-built facility for production of the HX50 helicopter. The project required a highly specialised combination of spray booth technology and bespoke composite manufacturing environments — delivered to aerospace specification.',
    client: 'Hills Helicopters',
    location: '',
    product: 'HX50 Helicopter',
    features: [
      'Poseidon Spray Booth — Raised floor for optimised airflow and superior refinishing precision. Full downdraught extraction ensuring a pristine, dust-free environment. Eco+ energy-saving modes.',
      'Paint Mixing Room — Dedicated space for precise colour matching and preparation, seamlessly integrated with the spray booth workflow.',
      'Temperature-Controlled Composite Rooms — Purpose-built spaces maintaining strict environmental conditions to preserve the integrity of composite materials critical to HX50 production.',
      'Relocated Oven — An existing Todd Engineering oven was relocated to the new facility, ensuring workflow continuity and operational efficiency.',
    ],
    quote: 'The installations from Todd Engineering have been instrumental in bringing our new facility to life. The Poseidon spray booth and composite rooms are essential to our operations. Todd Engineering\'s expertise and attention to detail have exceeded our expectations.',
    quoteAttr: 'Mark, Production Director — Hills Helicopters',
    gallery: [
      'https://www.toddengineering.co.uk/media/wridofho/img_4582.jpg',
      'https://www.toddengineering.co.uk/media/opfgeduw/img_4585.jpg',
      'https://www.toddengineering.co.uk/media/0ohpatmc/img_4586.jpg',
      'https://www.toddengineering.co.uk/media/qtcp3eoq/img_4580.jpg',
      'https://www.toddengineering.co.uk/media/nv1kjwg5/img_4583.jpg',
    ],
  },
  'sail-gp': {
    slug: 'sail-gp',
    title: 'Sail GP — Zeus All-Electric Spray Booth',
    sector: 'Marine',
    date: 'September 2024',
    hero: 'https://www.toddengineering.co.uk/media/dxkgo214/photo-2024-08-01-07-25-52.jpg',
    lead: 'Todd Engineering installed a bespoke Zeus all-electric commercial spray booth at Sail GP — the world\'s most exciting sailing championship. The booth was specifically tailored to meet the unique demands of Sail GP\'s operations, featuring far infrared curing technology and a drive-through design. Running entirely on renewable energy, it forms a central part of Sail GP\'s carbon-neutral operational strategy.',
    client: 'Sail GP',
    location: '',
    product: '',
    features: [
      'Zeus All-Electric Drive-Through Booth — Specifically engineered for Sail GP\'s high-performance vessels. Drive-through design allowing seamless operations with minimal turnaround downtime.',
      'Far Infrared Curing Technology — Penetrates at molecular level for efficient curing while maintaining lower part temperatures — crucial for performance composite materials.',
      'Side Extraction — Optimal airflow throughout the booth ensuring consistent finish quality.',
      'High & Low-Level Lighting — Full visibility across all surfaces for precision inspection and application.',
      'Renewable Energy Operation — Runs entirely on renewable energy as part of Sail GP\'s broader carbon-neutral commitment.',
    ],
    quote: '',
    quoteAttr: '',
    gallery: [
      'https://www.toddengineering.co.uk/media/x1lj40tc/photo-2024-08-01-07-25-05.jpg',
      'https://www.toddengineering.co.uk/media/oivbhcer/photo-2024-08-01-07-25-04.jpg',
      'https://www.toddengineering.co.uk/media/yxzpr5bi/photo-2024-08-01-07-25-05-8.jpg',
      'https://www.toddengineering.co.uk/media/nkbnhjux/photo-2024-08-01-07-25-05-9.jpg',
      'https://www.toddengineering.co.uk/media/3ryjzwej/photo-2024-08-01-07-25-05-7.jpg',
    ],
  },
  'wfel': {
    slug: 'wfel',
    title: 'WFEL — Boxer Armoured Vehicle Facility',
    sector: 'Defence',
    date: 'August 2024',
    hero: 'https://www.toddengineering.co.uk/media/djnnhlug/4d93414f-fc17-4b6c-bbf6-383936422a79.jpg',
    lead: 'WFEL, a global leader in defence manufacturing and producer of the iconic Boxer Armoured Vehicles, partnered with Todd Engineering to enhance their manufacturing capabilities with a purpose-built refinishing solution. The project demanded the highest standards of precision, durability and compliance with military-grade coating specifications.',
    client: 'WFEL',
    location: '',
    product: '',
    features: [
      'Titan CV Spray Booth — 26 metres long, two-stage drive-through design specifically for large-scale military vehicles. Full downdraught extraction for a pristine working environment.',
      'High, Mid & Low-Level Lighting — Ensuring flawless application and inspection capability across the entire vehicle surface.',
      'Centralised Inspection Pit — Integrated with comprehensive extraction systems for safe, efficient under-vehicle inspection to military-grade standards.',
      'Paint Mixing Room — Dedicated area for precise colour preparation and consistent coating quality.',
      'Plant Room — ABAC air compressor and WORKY dust extraction system providing full operational support infrastructure.',
    ],
    quote: 'The seamless integration of the Titan CV spray booth into our production line has significantly improved our throughput while maintaining the high standards essential for defence manufacturing.',
    quoteAttr: 'WFEL Team',
    gallery: [
      'https://www.toddengineering.co.uk/media/tslhr10r/5da4f4dc-6561-4ac3-a3cc-0071ae0c8781.jpg',
      'https://www.toddengineering.co.uk/media/2wqpgm1a/d55057f3-c099-433f-b3a0-0c7379f71c58.jpg',
      'https://www.toddengineering.co.uk/media/x13ng2do/50b22586-14fc-42f9-bf66-a809189c6d7b.jpg',
      'https://www.toddengineering.co.uk/media/bm2hokml/4f0f0043-9142-400f-ad57-6d456310e842.jpg',
      'https://www.toddengineering.co.uk/media/lpulbkoy/4.jpg',
    ],
  },
  'gemini-taunton': {
    slug: 'gemini-taunton',
    title: 'Gemini Taunton — Turnkey Installation',
    sector: 'Automotive',
    date: 'April 2025',
    hero: 'https://www.toddengineering.co.uk/media/djua12au/b6bb37d0-f229-4e66-bc42-e1a00e4585ef.jpg',
    lead: 'Todd Engineering delivered a comprehensive turnkey installation for Gemini Taunton, a long-standing customer. A temporary booth was installed to maintain full operational continuity while the new Zeus all-electric system was commissioned — demonstrating Todd Engineering\'s commitment to zero-downtime delivery.',
    client: 'Gemini Taunton',
    location: 'Taunton, UK',
    product: '',
    features: [
      'Zeus All-Electric Spray Booth — Far infrared curing technology, side-loading roller shutter door and all-electric operation aligned with carbon-neutral goals.',
      'Track & Skate System — Seamless vehicle movement from preparation through to the refinishing stage, significantly improving workflow.',
      'Dedicated Paint Mixing Room — Positioned adjacent to the spray booth for optimal efficiency and reduced turnaround.',
      'Temporary Olympian Booth — Installed during transition to maintain zero operational downtime throughout the project.',
    ],
    quote: 'Everything went and was fine yesterday, thank you. I would like to commend every one of you involved in the installation. From your good self to the guys who have been working so hard to complete the install. Please pass on my thanks!',
    quoteAttr: 'Stuart, General Manager — Gemini Taunton',
    gallery: [
      'https://www.toddengineering.co.uk/media/bqbjoy4a/135bc278-d040-4208-a395-cab781ea0ae4.jpg',
      'https://www.toddengineering.co.uk/media/q5qlcjft/1316bbc3-1e5e-4bf8-a8d7-a73223f47ff9.jpg',
      'https://www.toddengineering.co.uk/media/bh0hlq0r/ab482c7e-2c76-41d0-bcb6-01486395f027.jpg',
      'https://www.toddengineering.co.uk/media/wjyj3rn3/bd94f527-8998-42ce-882e-f4eaf88350b7.jpg',
      'https://www.toddengineering.co.uk/media/e3cjaugp/4ca7cfdf-63f2-43a3-bd1b-87a5c52e2070.jpg',
      'https://www.toddengineering.co.uk/media/mywccpl1/cd7e5a24-749c-4088-bcdb-d8ae968f8dfc.jpg',
    ],
  },
  'al-haddad-motors': {
    slug: 'al-haddad-motors',
    title: 'Al Haddad Motors — Mercedes-Benz Bahrain',
    sector: 'Export',
    date: 'February 2025',
    hero: 'https://www.toddengineering.co.uk/media/wufdmpr5/out.jpg',
    lead: 'Al Haddad Motors, the official Mercedes-Benz dealer in Bahrain with over 60 years of automotive excellence, partnered with Todd Engineering to deliver a full turnkey refinishing solution meeting the exacting standards of the Mercedes-Benz refinishing programme.',
    client: 'Al Haddad Motors',
    location: 'Bahrain',
    product: '',
    features: [
      'Zeus All-Electric Spray Booth — Advanced far infrared curing technology providing fast drying times and exceptional energy efficiency.',
      'Curing Oven with Roller Shutter Door — Positioned side-by-side with the spray booth for seamless transition between painting and curing phases.',
      'Track & Skate System — Effortless vehicle movement between each refinishing stage, minimising manual handling and technician workload.',
      'Twin Hades Preparation Booths — Positioned opposite the spray booth and oven for dust-free sanding, priming and masking before painting.',
      'Full Turnkey Delivery — Design, site planning, installation and commissioning managed end-to-end by Todd Engineering.',
    ],
    quote: 'Everything is great our end — the lads have been a credit to your company. Please pass on my thanks to each of them.',
    quoteAttr: 'Darren, Group Aftersales Manager — Al Haddad Motors',
    gallery: [
      'https://www.toddengineering.co.uk/media/fc2flvlb/img3.jpg',
      'https://www.toddengineering.co.uk/media/syba4n1s/img1.jpg',
      'https://www.toddengineering.co.uk/media/x4snoroa/img4.jpg',
      'https://www.toddengineering.co.uk/media/gupf5cbk/b59e37ec-8e40-4f25-9f6a-f69472884835.jpg',
      'https://www.toddengineering.co.uk/media/25jbcppl/ead55bfd-a0c9-4146-bc0a-ab99d153b4db.jpg',
      'https://www.toddengineering.co.uk/media/wrgkofl2/d8c2ad3e-e87a-4046-a68b-b79c189f5537.jpg',
    ],
  },
  'angus-mackinnon': {
    slug: 'angus-mackinnon',
    title: 'Angus MacKinnon — Carbon-Neutral Bodyshop',
    sector: 'Automotive',
    date: 'November 2024',
    hero: 'https://www.toddengineering.co.uk/media/iznnq2t3/img_4667.png',
    lead: 'Angus MacKinnon, a valued Todd Engineering customer for over two years, opened a purpose-built bodyshop in Uttoxeter with sustainability at the core of every decision. After witnessing the Zeus all-electric system in action at a neighbouring facility, owner Stuart committed to an all-electric setup with solar integration planned — setting a benchmark for the sector.',
    client: 'Angus MacKinnon',
    location: 'Uttoxeter, UK',
    product: '',
    features: [
      'Two Zeus Full Downdraught Spray Booths — All-electric operation eliminating fossil fuels entirely. Raised floor design for optimised airflow and superior finish quality.',
      'Far Infrared Curing Technology — Cures paint at molecular level for faster drying times and measurably lower energy consumption.',
      'Paint Mixing Room — Advanced controls for seamless workflow and precise colour matching.',
      'Compressor System — High-performance air supply consistent across all refinishing processes.',
      'Solar Integration (Planned) — Facility designed to integrate solar energy, targeting fully renewable-powered operation.',
    ],
    quote: '',
    quoteAttr: '',
    gallery: [
      'https://www.toddengineering.co.uk/media/ysrh0ugw/img_4657.png',
      'https://www.toddengineering.co.uk/media/d4gdut0w/img_4649.png',
      'https://www.toddengineering.co.uk/media/ixliukf5/img_4652.png',
      'https://www.toddengineering.co.uk/media/snedrxcn/img_4648.png',
      'https://www.toddengineering.co.uk/media/minlsltr/img_4659.png',
    ],
  },
  'rhodes': {
    slug: 'rhodes',
    title: 'Rhodes — Carbon-Neutral Facility',
    sector: 'Automotive',
    date: 'November 2024',
    hero: 'https://www.toddengineering.co.uk/media/0bgj5ymj/1729781701010.jpeg',
    lead: 'Rhodes Accident Repair Centre in Rugeley has been a long-standing Todd Engineering customer. Their new purpose-built facility in Rugeley was designed from the ground up to achieve carbon neutrality — combining an all-electric Todd Engineering setup with solar battery storage to minimise grid reliance.',
    client: 'Rhodes Accident Repair Centre',
    location: '',
    product: '',
    features: [
      'Zeus Spray Booth — Centrally positioned with twin-loading roller shutter doors for enhanced access and operational flexibility.',
      'Two Hades Preparation Booths — Advanced airflow and extraction for clean, efficient vehicle preparation seamlessly integrated into the workflow.',
      'Paint Mixing Room — Centralised controls ensuring precise colour matching and ease of operation.',
      'Compressor System — Full support for all operational processes throughout the facility.',
      'Solar Battery Storage — Complementing the all-electric setup to reduce grid reliance and support carbon-neutral ambitions.',
    ],
    quote: 'The new facility has exceeded our expectations. Todd Engineering\'s expertise and top-quality equipment have been pivotal in creating a carbon-neutral setup that meets our operational needs while supporting our sustainability goals.',
    quoteAttr: 'Freddie, Bodyshop Manager — Rhodes Accident Repair Centre',
    gallery: [
      'https://www.toddengineering.co.uk/media/lacm5krh/img_6502.jpg',
      'https://www.toddengineering.co.uk/media/ydvogcpr/img_6499.jpg',
      'https://www.toddengineering.co.uk/media/wttl0rv3/img_6498.jpg',
      'https://www.toddengineering.co.uk/media/gn2nhngd/img_6514.jpg',
      'https://www.toddengineering.co.uk/media/mxtjekoo/img_6494.jpg',
      'https://www.toddengineering.co.uk/media/qval1ia1/img_6508.jpg',
    ],
  },
  'rmd-kwikform': {
    slug: 'rmd-kwikform',
    title: 'RMD Kwikform — Titan CV Installation',
    sector: 'Industrial',
    date: 'February 2025',
    hero: 'https://www.toddengineering.co.uk/media/fpkhzkzl/49efedba-b3f9-4d7d-9496-0f4008c5ef61.jpg',
    lead: 'RMD Kwikform, a global leader in formwork, falsework and ground shoring solutions, required a high-performance, purpose-built spray booth to meet their exacting industrial refinishing standards. Todd Engineering delivered a Titan CV drive-through system with BAXT wall protection and a dedicated operator training programme.',
    client: 'RMD Kwikform',
    location: '',
    product: '',
    features: [
      'Titan CV Drive-Through Spray Booth — Customised for industrial workflow, enabling vehicles and equipment to pass through without interruption.',
      'Side Extraction System — Superior airflow maintaining a clean working environment and consistent finish quality.',
      'High & Low-Level LED Lighting — Optimal visibility across all surfaces, reducing shadows for precision application.',
      'BAXT 5-Layer Wall Protection — Self-adhesive peel-away layers extending booth lifespan and reducing maintenance downtime.',
      'Dedicated Operator Training — Hands-on programme covering operation, safety protocols and maintenance best practices.',
    ],
    quote: '',
    quoteAttr: '',
    gallery: [
      'https://www.toddengineering.co.uk/media/t10nzhoq/d8a447f2-5d06-4352-ad13-04b31c852b62.jpg',
      'https://www.toddengineering.co.uk/media/41xd1uja/c1743c58-c672-4e15-b3ed-326bf853e8f3.jpg',
      'https://www.toddengineering.co.uk/media/hzehdbfc/a722c0db-0b21-4c24-afde-7f2bba40bf1f.jpg',
      'https://www.toddengineering.co.uk/media/tkmmmctl/6579b92b-ea41-489e-9a79-50d35e12a14a.jpg',
      'https://www.toddengineering.co.uk/media/cltfekzf/627c64f5-5b58-4be2-9d2c-7889fae10ea6.jpg',
    ],
  },
  'hgv-solutions': {
    slug: 'hgv-solutions',
    title: 'HGV Solutions — Zeus Commercial Booth',
    sector: 'Industrial',
    date: 'November 2024',
    hero: 'https://www.toddengineering.co.uk/media/vlwgsbjn/de3f3394-bf58-43d7-b0ab-1112b14c2570.png',
    lead: 'HGV Solutions has been at the forefront of sustainable refinishing adoption, transitioning from gas-fired booths to Zeus all-electric systems since 2022. This installation of the first Zeus Commercial Spray Booth — purpose-built for large commercial vehicles — marks the latest chapter in an ongoing partnership with Todd Engineering.',
    client: 'HGV Solutions',
    location: '',
    product: '',
    features: [
      'Zeus Commercial Spray Booth — 32m long × 5.5m wide × 6.5m high. Specifically engineered for large commercial vehicles with all-electric operation.',
      'Far Infrared (FIR) Technology — Molecular-level paint curing, faster drying times, lower panel temperatures ideal for commercial vehicle surfaces.',
      'All-Electric Operation — Completely eliminating fossil fuel use in line with HGV Solutions\' long-term sustainability strategy.',
      'Eco+ Energy Saving Modes — Automated energy management reducing operational costs while maintaining peak performance.',
      'Custom Dimensions — Engineered to HGV Solutions\' exact site and workflow requirements.',
    ],
    quote: '',
    quoteAttr: '',
    gallery: [
      'https://www.toddengineering.co.uk/media/udqjxjnh/ecaea07d-70b1-4651-b270-634ebd96a07c.jpg',
      'https://www.toddengineering.co.uk/media/eszfvotr/b51d30a0-55ed-4537-8987-d0513a2179a7.jpg',
      'https://www.toddengineering.co.uk/media/zesjdowe/e19a5423-bd35-4348-a731-229f64b7a10e.jpg',
      'https://www.toddengineering.co.uk/media/jioatejd/deda1b13-993e-41b0-a176-a2bdc1c40bc7.jpg',
      'https://www.toddengineering.co.uk/media/vvufd4y1/6ef93cd6-1a59-426c-a76f-0c3838713ba5.jpg',
    ],
  },
  'autolux': {
    slug: 'autolux',
    title: 'Autolux Body & Paint — Sustainable Upgrade',
    sector: 'Automotive',
    date: 'October 2024',
    hero: 'https://www.toddengineering.co.uk/media/0p1e0lvn/462264937_122122202240454025_4076624584352154895_n.jpg',
    lead: 'Autolux Body & Paint, a premier accident repair centre committed to high-quality repairs and environmental responsibility, partnered with Todd Engineering to install a state-of-the-art all-electric Nemesis setup — dramatically improving workflow efficiency and sustainability performance.',
    client: 'Autolux Body & Paint',
    location: '',
    product: '',
    features: [
      '2× Zeus All-Electric Spray Booths — Far infrared technology for energy-efficient curing and faster turnaround times.',
      '2× Hades Preparation Booths — Superior air extraction systems for clean, efficient vehicle preparation.',
      'Paint Mixing Room — Fully equipped for optimal colour accuracy and precision matching.',
      'Compressor System — High-performance air supply supporting all refinishing processes.',
      'Plant Room — Housing all critical equipment with additional operational storage.',
    ],
    quote: '',
    quoteAttr: '',
    gallery: [],
  },
  'jet-glow': {
    slug: 'jet-glow',
    title: 'Jet Glow — Integrated Refinishing Solution',
    sector: 'Automotive',
    date: 'October 2024',
    hero: 'https://www.toddengineering.co.uk/media/agslr5np/photo-2024-08-02-12-48-05-6.jpg',
    lead: 'Jet Glow approached Todd Engineering to upgrade their facilities with a tailored solution aimed at optimising workflow and boosting throughput. Todd Engineering designed and installed a fully integrated multi-booth system where roller shutter doors connect each stage — creating a seamless path from preparation through to final finish.',
    client: 'Jet Glow',
    location: '',
    product: '',
    features: [
      '2× Zeus Preparation Booths — Electrically heated for consistent, efficient preparation. Designed to support high-volume operations.',
      '1× Titan Spray Booth — Robust performance and precision delivery, fully integrated into the sequential workflow.',
      'Roller Shutter Connection System — Connecting all three booths for effortless vehicle movement between stages.',
      'WORKY Dust Extraction System — Flush-mounted within preparation booth walls for a clean working environment.',
      'Paint Mixing Room — Strategically placed for easy access and precise colour preparation.',
    ],
    quote: 'Since the installation, we\'ve seen significant improvements in our operational flow and productivity.',
    quoteAttr: 'Jet Glow Team',
    gallery: [
      'https://www.toddengineering.co.uk/media/z4wbyxr2/photo-2024-08-02-12-48-05-2.jpg',
      'https://www.toddengineering.co.uk/media/0eyh4yxj/photo-2024-08-02-12-48-05-1.jpg',
      'https://www.toddengineering.co.uk/media/uiahrgyv/photo-2024-08-02-12-48-05-5.jpg',
      'https://www.toddengineering.co.uk/media/syqd0puh/photo-2024-08-02-12-48-05-9.jpg',
      'https://www.toddengineering.co.uk/media/r4bo2yrj/photo-2024-08-02-12-48-05-12.jpg',
    ],
  },
  'mg-accident-repair': {
    slug: 'mg-accident-repair',
    title: 'MG Accident Repair Centre — Zeus Upgrade',
    sector: 'Automotive',
    date: 'July 2024',
    hero: 'https://www.toddengineering.co.uk/media/a0khul2b/dsc07408.png',
    lead: 'MG Accident Repair Centre upgraded from their existing Spartan booth to the Zeus all-electric system — driven by carbon-neutral goals, PAS 2060 compliance ambitions and the desire to reclaim space previously occupied by a gas bulk tank. The results exceeded expectations across every metric.',
    client: 'MG Accident Repair Centre',
    location: '',
    product: '',
    features: [
      'Zeus All-Electric Spray Booth — Superior performance, energy efficiency and environmental credentials.',
      'Elimination of Gas Infrastructure — Removal of the gas bulk tank reclaiming significant floor space.',
      'PAS 2060 Compliance Support — All-electric operation directly supporting carbon-neutral certification.',
      'Reduced Drying Times — Far infrared technology delivering faster cycle times and increased throughput.',
      '50% Productivity Increase — Reported following the transition to the Zeus system.',
    ],
    quote: '',
    quoteAttr: '',
    gallery: [
      'https://www.toddengineering.co.uk/media/l2skezjo/img_2532.jpg',
      'https://www.toddengineering.co.uk/media/wfjpoy5t/img_2548-1.jpg',
      'https://www.toddengineering.co.uk/media/duql313o/img_2547-1.jpg',
      'https://www.toddengineering.co.uk/media/4ztn2hio/img_2553.jpg',
      'https://www.toddengineering.co.uk/media/suxi5kwp/1.jpg',
    ],
  },
}
