export interface ProjectData {
  slug: string
  title: string
  client_name: string
  sector: string
  cover_image_url: string
  outcome_stats: { label: string; value: string }[]
  brief: string
  solution: string
  testimonial_quote?: string
  testimonial_author?: string
}

export const PROJECTS_DATA: Record<string, ProjectData> = {
  'k-and-s': {
    slug: 'k-and-s',
    title: 'Maximising Workshop Space with a Bespoke Zeus Spraybooth Installation',
    client_name: 'K&S',
    sector: 'Automotive Repair & Refinishing',
    cover_image_url: '/media/zeus-xr-21.jpg',
    outcome_stats: [
      { label: 'Workshop Space', value: 'Maximised' },
      { label: 'Heating System', value: 'Fully Electric' },
      { label: 'Vehicle Transfer', value: 'Track & Skate' },
      { label: 'Gas Dependency', value: 'Eliminated' },
    ],
    brief: 'K&S required a modern paint finishing solution that would maximise productivity without compromising the limited floor space available within their workshop. A conventional spraybooth configuration would have restricted vehicle movement and reduced the available working area — the challenge was to deliver a solution that maintained an efficient paint process while making the best possible use of the existing building footprint.',
    solution: 'Working closely with K&S, Todd Engineering designed and installed a bespoke Zeus Spraybooth complete with a dedicated paint mixing room. To optimise the available space, the booth was configured with the roller shutter door positioned across the full width rather than the traditional end-entry arrangement. The installation incorporated our Track & Skate System, allowing vehicles to be loaded onto purpose-designed skates outside the booth and transferred smoothly along a guided track — improving positioning accuracy and reducing manoeuvring. The Zeus Spraybooth operates on a fully electric system, eliminating the need for gas and reducing running costs and emissions.',
    testimonial_quote: 'Todd Engineering designed the system around our specific operational requirements and building constraints, ensuring the final solution worked seamlessly within the available space.',
    testimonial_author: 'K&S, Automotive Repair & Refinishing',
  },
  'uk-offshore-wind-farm': {
    slug: 'uk-offshore-wind-farm',
    title: 'UK Offshore Wind Farm — Large-Format Industrial Finishing Facility',
    client_name: 'Seah Wind',
    sector: 'Renewable Energy',
    cover_image_url: '/media/windfarm.png',
    outcome_stats: [
      { label: 'Project Duration', value: '18 Months' },
      { label: 'Booth Type', value: 'Bespoke Large-Format' },
      { label: 'Sector', value: 'Renewable Energy' },
      { label: 'Delivery', value: 'Turnkey' },
    ],
    brief: 'The project required a purpose-built finishing facility capable of accommodating large-format wind turbine components — a scale and specification far beyond standard automotive or industrial spraybooth installations. Environmental performance, coating quality and operational throughput were all critical requirements.',
    solution: 'Todd Engineering engineered a bespoke large-format finishing environment with custom airflow, heating and filtration systems designed specifically for the dimensions and coating requirements of offshore wind components. The entire project was delivered as a turnkey installation over an 18-month programme, with our team managing all aspects of design, manufacture, installation and commissioning.',
    testimonial_quote: 'The Todd Engineering team delivered a genuinely bespoke solution — engineered to our exact specification and delivered on time.',
    testimonial_author: 'Seah Wind, Renewable Energy',
  },
  'bahrain-aerospace-facility': {
    slug: 'bahrain-aerospace-facility',
    title: 'Bahrain Aerospace Facility — Precision Finishing Environment',
    client_name: 'Al Haddad Motors',
    sector: 'Aerospace',
    cover_image_url: '/media/aerospace.png',
    outcome_stats: [
      { label: 'Location', value: 'Bahrain' },
      { label: 'Standard', value: 'Aerospace Grade' },
      { label: 'Delivery', value: 'International Export' },
      { label: 'Type', value: 'Bespoke Design & Build' },
    ],
    brief: 'A leading aerospace operation in Bahrain required a precision finishing environment capable of meeting the exacting standards required for aerospace-grade components. The facility needed to deliver consistent, controlled finishing conditions for MRO operations in a demanding Middle East environment.',
    solution: 'Todd Engineering designed and manufactured a bespoke precision finishing system engineered to aerospace standards — including controlled airflow, temperature and humidity management. The system was fully manufactured in the UK before being exported and commissioned by our team on-site in Bahrain, ensuring that our standards of quality and precision were maintained throughout the entire project lifecycle.',
  },
  'sandal-bmw': {
    slug: 'sandal-bmw',
    title: 'Sandal BMW — Dual Poseidon Installation',
    client_name: 'Sandal BMW',
    sector: 'Automotive',
    cover_image_url: 'https://www.toddengineering.co.uk/media/o5bdbnbj/img_3891.png',
    outcome_stats: [
      { label: 'Booths Installed', value: '2 Units' },
      { label: 'System', value: 'Poseidon Series' },
      { label: 'Heating', value: 'Hydra-Cure™' },
      { label: 'Operation', value: 'Fully Electric' },
    ],
    brief: 'Sandal BMW required a high-throughput finishing solution to support the demands of a busy franchised BMW and MINI bodyshop. Consistent, premium finish quality was non-negotiable — both for customer satisfaction and brand compliance.',
    solution: 'Todd Engineering supplied and installed dual Poseidon spraybooths — providing the throughput and performance required for a busy BMW operation. The Poseidon\'s Hydra-Cure™ water-based curing system and intelligent temperature control deliver the consistent finish quality that prestige automotive brands demand.',
  },
  'smallest-cog': {
    slug: 'smallest-cog',
    title: 'The Smallest COG — Richard Hammond\'s Workshop',
    client_name: 'The Smallest Cog',
    sector: 'Automotive',
    cover_image_url: 'https://www.toddengineering.co.uk/media/3emjgs10/eob_2047eob.jpg',
    outcome_stats: [
      { label: 'Profile', value: 'High-Profile Installation' },
      { label: 'System', value: 'Zeus Platform' },
      { label: 'Specification', value: 'Bespoke' },
      { label: 'Standard', value: 'Premium' },
    ],
    brief: 'Richard Hammond\'s award-winning restoration workshop required a finishing facility that matched the standards of the world-class vehicles they restore — with the same attention to detail and quality that defines their work.',
    solution: 'Todd Engineering specified and installed a Zeus platform spraybooth for The Smallest Cog — providing a premium, electric finishing environment that complements the workshop\'s reputation for exceptional craftsmanship. The installation was tailored to the unique requirements of a specialist restoration facility.',
    testimonial_quote: 'The spraybooth had to match the quality of the vehicles we restore. Todd Engineering delivered exactly that.',
    testimonial_author: 'The Smallest Cog',
  },
  'hills-helicopters': {
    slug: 'hills-helicopters',
    title: 'Hills Helicopters — HX50 Facility',
    client_name: 'Hills Helicopters',
    sector: 'Aerospace',
    cover_image_url: 'https://www.toddengineering.co.uk/media/tqqcixtw/img_4588.jpg',
    outcome_stats: [
      { label: 'Sector', value: 'Aerospace' },
      { label: 'Application', value: 'Helicopter Manufacturing' },
      { label: 'System', value: 'Bespoke Design' },
      { label: 'Standard', value: 'Aerospace Compliant' },
    ],
    brief: 'Hills Helicopters required a purpose-built finishing environment for their HX50 helicopter manufacturing programme — a facility capable of meeting aerospace-grade finishing standards for composite and aluminium components.',
    solution: 'Todd Engineering designed a bespoke finishing facility to the specific requirements of Hills Helicopters\' HX50 programme. The system provides controlled airflow, filtration and temperature management at the level required for aerospace manufacturing — delivered on time and to full specification.',
  },
  'sail-gp': {
    slug: 'sail-gp',
    title: 'Sail GP — Zeus All-Electric Booth',
    client_name: 'Sail GP',
    sector: 'Marine',
    cover_image_url: 'https://www.toddengineering.co.uk/media/dxkgo214/photo-2024-08-01-07-25-52.jpg',
    outcome_stats: [
      { label: 'System', value: 'Zeus All-Electric' },
      { label: 'Sector', value: 'Marine / Motorsport' },
      { label: 'Heating', value: 'FIR Electric' },
      { label: 'Gas Usage', value: 'Zero' },
    ],
    brief: 'Sail GP demanded a finishing solution capable of delivering high-specification coating results on performance marine components — with sustainability credentials that matched the championship\'s environmental commitments.',
    solution: 'Todd Engineering supplied a Zeus all-electric spraybooth — eliminating gas entirely while delivering the controlled finishing environment required for performance marine applications. The system\'s far infrared curing and precise airflow management provide consistent results across a range of marine coating processes.',
  },
  'wfel': {
    slug: 'wfel',
    title: 'WFEL — Boxer Armoured Vehicle Facility',
    client_name: 'WFEL',
    sector: 'Defence',
    cover_image_url: 'https://www.toddengineering.co.uk/media/djnnhlug/4d93414f-fc17-4b6c-bbf6-383936422a79.jpg',
    outcome_stats: [
      { label: 'Sector', value: 'Defence' },
      { label: 'Application', value: 'Armoured Vehicle Finishing' },
      { label: 'Scale', value: 'Large Format' },
      { label: 'Standard', value: 'Defence Grade' },
    ],
    brief: 'WFEL required a large-format finishing facility capable of accommodating Boxer armoured vehicles for their UK manufacturing programme — a highly specialised application demanding exceptional airflow, coating control and operational reliability.',
    solution: 'Todd Engineering engineered a bespoke large-format spraybooth to the exacting requirements of armoured vehicle finishing. The system provides the controlled environment, airflow capacity and heating performance required for defence-grade coatings — designed and installed to meet WFEL\'s programme requirements.',
  },
  'gemini-taunton': {
    slug: 'gemini-taunton',
    title: 'Gemini Taunton — Comprehensive Turnkey Installation',
    client_name: 'Gemini Taunton',
    sector: 'Automotive',
    cover_image_url: 'https://www.toddengineering.co.uk/media/djua12au/b6bb37d0-f229-4e66-bc42-e1a00e4585ef.jpg',
    outcome_stats: [
      { label: 'Delivery', value: 'Turnkey' },
      { label: 'Sector', value: 'Automotive' },
      { label: 'Scope', value: 'Full Site Project' },
      { label: 'Support', value: 'Ongoing' },
    ],
    brief: 'Gemini Taunton required a comprehensive turnkey spraybooth installation — including booth supply, site preparation, ventilation, electrical and full commissioning — delivered to the highest standard for their busy automotive bodyshop operation.',
    solution: 'Todd Engineering managed the entire project from initial survey through to handover, delivering a complete turnkey installation. The project covered all aspects of site preparation, structural work, booth installation and commissioning — providing Gemini with a ready-to-operate finishing facility backed by our nationwide service and support network.',
  },
  'al-haddad-motors': {
    slug: 'al-haddad-motors',
    title: 'Al Haddad Motors — Mercedes-Benz Bahrain',
    client_name: 'Al Haddad Motors',
    sector: 'Export / Automotive',
    cover_image_url: 'https://www.toddengineering.co.uk/media/wufdmpr5/out.jpg',
    outcome_stats: [
      { label: 'Location', value: 'Bahrain' },
      { label: 'Brand', value: 'Mercedes-Benz' },
      { label: 'Project Type', value: 'International Export' },
      { label: 'Delivery', value: 'Turnkey' },
    ],
    brief: 'As the official Mercedes-Benz dealer in Bahrain, Al Haddad Motors required a finishing facility that met the exacting standards of the Mercedes-Benz brand and its approved bodyshop programme.',
    solution: 'Todd Engineering designed, manufactured and exported a complete finishing facility to Bahrain — meeting all Mercedes-Benz approved repairer specifications. Our team managed the international logistics and on-site commissioning, ensuring the completed facility delivered the performance and compliance required from day one.',
  },
  'angus-mackinnon': {
    slug: 'angus-mackinnon',
    title: 'Angus MacKinnon — Carbon-Neutral Bodyshop Partnership',
    client_name: 'Angus MacKinnon',
    sector: 'Automotive',
    cover_image_url: 'https://www.toddengineering.co.uk/media/iznnq2t3/img_4667.png',
    outcome_stats: [
      { label: 'System', value: 'All Electric Zeus' },
      { label: 'Carbon Footprint', value: 'Reduced' },
      { label: 'Gas Usage', value: 'Eliminated' },
      { label: 'Initiative', value: 'Carbon-Neutral Bodyshop' },
    ],
    brief: 'Angus MacKinnon were pursuing a carbon-neutral bodyshop operation — requiring a finishing solution that would eliminate gas usage entirely while delivering the throughput and finish quality expected from a leading automotive retailer.',
    solution: 'Todd Engineering supplied an all-electric Zeus spraybooth as the cornerstone of Angus MacKinnon\'s sustainability programme. By eliminating gas heating entirely and switching to far infrared electric curing, the installation achieved a significant reduction in operational carbon footprint — while improving energy efficiency and maintaining premium finish standards.',
  },
  'rhodes': {
    slug: 'rhodes',
    title: 'Rhodes — Carbon-Neutral Facility',
    client_name: 'Rhodes Accident Repair',
    sector: 'Automotive',
    cover_image_url: 'https://www.toddengineering.co.uk/media/0bgj5ymj/1729781701010.jpeg',
    outcome_stats: [
      { label: 'System', value: 'Zeus Platform' },
      { label: 'Emissions', value: 'Reduced' },
      { label: 'Heating', value: 'All Electric FIR' },
      { label: 'Gas', value: 'Eliminated' },
    ],
    brief: 'Rhodes Accident Repair were committed to reducing the environmental impact of their operations and required a spraybooth system that aligned with their sustainability goals without compromising finish quality or throughput.',
    solution: 'Todd Engineering installed a Zeus all-electric spraybooth at the Rhodes facility, replacing gas heating with far infrared electric curing. The installation delivered immediate reductions in energy consumption and emissions — part of a wider commitment to sustainable automotive repair.',
  },
  'rmd-kwikform': {
    slug: 'rmd-kwikform',
    title: 'RMD Kwikform — Titan CV Industrial Installation',
    client_name: 'RMD Kwikform',
    sector: 'Industrial',
    cover_image_url: 'https://www.toddengineering.co.uk/media/fpkhzkzl/49efedba-b3f9-4d7d-9496-0f4008c5ef61.jpg',
    outcome_stats: [
      { label: 'System', value: 'Titan CV Series' },
      { label: 'Application', value: 'Industrial / HGV' },
      { label: 'Capacity', value: 'Large Format' },
      { label: 'Delivery', value: 'Turnkey' },
    ],
    brief: 'RMD Kwikform required an industrial finishing solution capable of accommodating large-format construction and scaffolding equipment — a high-demand application requiring a purpose-built, heavy-duty spraybooth system.',
    solution: 'Todd Engineering supplied a Titan CV series industrial spraybooth — specifically engineered for large commercial vehicle and equipment finishing. The system provides the airflow capacity, dimensions and heating performance required for heavy industrial coatings, installed as a complete turnkey solution.',
  },
  'hgv-solutions': {
    slug: 'hgv-solutions',
    title: 'HGV Solutions — Zeus Commercial Booth',
    client_name: 'HGV Solutions',
    sector: 'Industrial',
    cover_image_url: 'https://www.toddengineering.co.uk/media/vlwgsbjn/de3f3394-bf58-43d7-b0ab-1112b14c2570.png',
    outcome_stats: [
      { label: 'System', value: 'Zeus Commercial' },
      { label: 'Application', value: 'HGV Finishing' },
      { label: 'Format', value: 'Extra Large' },
      { label: 'Operation', value: 'All Electric' },
    ],
    brief: 'HGV Solutions required a large-format finishing facility capable of handling full-size heavy goods vehicles — an application demanding extra-large booth dimensions, high-capacity airflow and robust heating performance.',
    solution: 'Todd Engineering supplied a Zeus commercial-format spraybooth engineered specifically for HGV applications. The system accommodates full-size lorries and commercial vehicles while delivering the consistent airflow and heating performance required for commercial vehicle refinishing.',
  },
  'autolux': {
    slug: 'autolux',
    title: 'Autolux Body & Paint — Sustainable Upgrade',
    client_name: 'Autolux Body & Paint',
    sector: 'Automotive',
    cover_image_url: 'https://www.toddengineering.co.uk/media/0p1e0lvn/462264937_122122202240454025_4076624584352154895_n.jpg',
    outcome_stats: [
      { label: 'System', value: 'Zeus All-Electric' },
      { label: 'Upgrade', value: 'Gas Elimination' },
      { label: 'Energy', value: 'Reduced' },
      { label: 'Finish', value: 'Premium' },
    ],
    brief: 'Autolux Body & Paint were looking to upgrade their finishing operation — moving to a more sustainable, lower-running-cost solution without sacrificing the finish quality their customers expect.',
    solution: 'Todd Engineering delivered a Zeus all-electric spraybooth upgrade at the Autolux facility, removing gas dependency and reducing ongoing energy costs while improving the consistency and quality of the finished product through FIR electric curing technology.',
  },
  'jet-glow': {
    slug: 'jet-glow',
    title: 'Jet Glow — Integrated Finishing Solution',
    client_name: 'Jet Glow',
    sector: 'Automotive',
    cover_image_url: 'https://www.toddengineering.co.uk/media/agslr5np/photo-2024-08-02-12-48-05-6.jpg',
    outcome_stats: [
      { label: 'System', value: 'Integrated Solution' },
      { label: 'Throughput', value: 'Increased' },
      { label: 'Quality', value: 'Premium' },
      { label: 'Support', value: 'Ongoing' },
    ],
    brief: 'Jet Glow required a fully integrated finishing solution to support their growing operation — delivering premium results consistently while improving throughput and workflow efficiency across their bodyshop.',
    solution: 'Todd Engineering specified and installed a complete integrated finishing solution for Jet Glow — combining spraybooth, prep bay and mixing room into a coordinated system. The installation was designed around the specific workflow of the Jet Glow operation, backed by our full commissioning service and ongoing technical support.',
  },
  'mg-accident-repair': {
    slug: 'mg-accident-repair',
    title: 'MG Accident Repair Centre — Carbon-Neutral Partnership',
    client_name: 'MG Accident Repair',
    sector: 'Automotive',
    cover_image_url: 'https://www.toddengineering.co.uk/media/a0khul2b/dsc07408.png',
    outcome_stats: [
      { label: 'Initiative', value: 'Carbon-Neutral' },
      { label: 'System', value: 'Zeus Electric' },
      { label: 'Emissions', value: 'Significantly Reduced' },
      { label: 'Partnership', value: 'Ongoing' },
    ],
    brief: 'MG Accident Repair Centres were committed to a carbon-neutral partnership programme — requiring a finishing solution that would deliver measurable reductions in emissions and energy consumption across their network.',
    solution: 'Todd Engineering partnered with MG Accident Repair to deliver an all-electric Zeus spraybooth solution supporting their carbon-neutral programme. The installation eliminated gas heating in favour of FIR electric curing — delivering a significant reduction in the environmental footprint of their finishing operations.',
    testimonial_quote: 'The Zeus electric system has been central to our carbon-neutral programme. The energy savings and emissions reductions have exceeded our expectations.',
    testimonial_author: 'MG Accident Repair Centre',
  },
}

export const PROJECTS_LIST = Object.values(PROJECTS_DATA)
