export interface ProjectData {
  slug: string
  title: string
  client_name: string
  sector: string
  cover_image_url: string
  gallery_images?: string[]
  outcome_stats: { label: string; value: string }[]
  brief: string
  solution: string
  testimonial_quote?: string
  testimonial_author?: string
}

export const PROJECTS_DATA: Record<string, ProjectData> = {
  'k-and-s': {
    slug: 'k-and-s',
    title: 'Maximising Workshop Space with a Bespoke Zeus Spraybooth Installation',
    client_name: 'K&S',
    sector: 'Automotive Repair & Refinishing',
    cover_image_url: '/media/projects/k-and-s/23.jpg',
    gallery_images: [
      '/media/projects/k-and-s/23.jpg',
      '/media/projects/k-and-s/24.jpg',
      '/media/projects/k-and-s/25.jpg',
      '/media/projects/k-and-s/26.jpg',
      '/media/projects/k-and-s/27.jpg',
    ],
    outcome_stats: [
      { label: 'Workshop Space', value: 'Maximised' },
      { label: 'Heating System', value: 'Fully Electric' },
      { label: 'Vehicle Transfer', value: 'Track & Skate' },
      { label: 'Gas Dependency', value: 'Eliminated' },
    ],
    brief: 'K&S required a modern paint finishing solution that would maximise productivity without compromising the limited floor space available within their workshop. A conventional spraybooth configuration would have restricted vehicle movement and reduced the available working area — the challenge was to deliver a solution that maintained an efficient paint process while making the best possible use of the existing building footprint.',
    solution: 'Working closely with K&S, Todd Engineering designed and installed a bespoke Zeus Spraybooth complete with a dedicated paint mixing room. To optimise the available space, the booth was configured with the roller shutter door positioned across the full width rather than the traditional end-entry arrangement. The installation incorporated our Track & Skate System, allowing vehicles to be loaded onto purpose-designed skates outside the booth and transferred smoothly along a guided track — improving positioning accuracy and reducing manoeuvring. The Zeus Spraybooth operates on a fully electric system, eliminating the need for gas and reducing running costs and emissions.',
    testimonial_quote: 'Todd Engineering designed the system around our specific operational requirements and building constraints, ensuring the final solution worked seamlessly within the available space.',
    testimonial_author: 'K&S, Automotive Repair & Refinishing',
  },
  'uk-offshore-wind-farm': {
    slug: 'uk-offshore-wind-farm',
    title: 'UK Offshore Wind Farm — Large-Format Industrial Finishing Facility',
    client_name: 'Seah Wind',
    sector: 'Renewable Energy',
    cover_image_url: '/media/windfarm.png',
    outcome_stats: [
      { label: 'Project Duration', value: '18 Months' },
      { label: 'Booth Type', value: 'Bespoke Large-Format' },
      { label: 'Sector', value: 'Renewable Energy' },
      { label: 'Delivery', value: 'Turnkey' },
    ],
    brief: 'The project required a purpose-built finishing facility capable of accommodating large-format wind turbine components — a scale and specification far beyond standard automotive or industrial spraybooth installations. Environmental performance, coating quality and operational throughput were all critical requirements.',
    solution: 'Todd Engineering engineered a bespoke large-format finishing environment with custom airflow, heating and filtration systems designed specifically for the dimensions and coating requirements of offshore wind components. The entire project was delivered as a turnkey installation over an 18-month programme, with our team managing all aspects of design, manufacture, installation and commissioning.',
    testimonial_quote: 'The Todd Engineering team delivered a genuinely bespoke solution — engineered to our exact specification and delivered on time.',
    testimonial_author: 'Seah Wind, Renewable Energy',
  },
  'bahrain-aerospace-facility': {
    slug: 'bahrain-aerospace-facility',
    title: 'Bahrain Aerospace Facility — Precision Finishing Environment',
    client_name: 'Al Haddad Motors',
    sector: 'Aerospace',
    cover_image_url: '/media/aerospace.png',
    outcome_stats: [
      { label: 'Location', value: 'Bahrain' },
      { label: 'Standard', value: 'Aerospace Grade' },
      { label: 'Delivery', value: 'International Export' },
      { label: 'Type', value: 'Bespoke Design & Build' },
    ],
    brief: 'A leading aerospace operation in Bahrain required a precision finishing environment capable of meeting the exacting standards required for aerospace-grade components. The facility needed to deliver consistent, controlled finishing conditions for MRO operations in a demanding Middle East environment.',
    solution: 'Todd Engineering designed and manufactured a bespoke precision finishing system engineered to aerospace standards — including controlled airflow, temperature and humidity management. The system was fully manufactured in the UK before being exported and commissioned by our team on-site in Bahrain, ensuring that our standards of quality and precision were maintained throughout the entire project lifecycle.',
  },
  'sandal-bmw': {
    slug: 'sandal-bmw',
    title: 'Sandal BMW — Dual Poseidon Installation',
    client_name: 'Sandal BMW',
    sector: 'Automotive',
    cover_image_url: '/media/projects/sandal-bmw/hero.png',
    gallery_images: [
      '/media/projects/sandal-bmw/hero.png',
      '/media/projects/sandal-bmw/gallery-1.jpg',
      '/media/projects/sandal-bmw/gallery-2.jpg',
      '/media/projects/sandal-bmw/gallery-3.jpg',
      '/media/projects/sandal-bmw/gallery-4.png',
      '/media/projects/sandal-bmw/gallery-5.png',
    ],
    outcome_stats: [
      { label: 'Booths Installed', value: '2× Poseidon' },
      { label: 'Technology', value: 'Hydracure + Eco+' },
      { label: 'Downtime', value: 'Zero' },
      { label: 'Date', value: 'July 2024' },
    ],
    brief: 'Sandal BMW & MINI required an OEM-compliant finishing upgrade capable of handling high volumes without a single day of downtime. The installation had to meet BMW\'s exacting bodyshop programme standards for finish quality, colour accuracy and production throughput.',
    solution: 'Todd Engineering delivered a meticulously planned phased installation of two Poseidon low-profile full-downdraught spray booths, a bespoke paint mixing room with shelving and extraction bench, a dedicated gun wash room, and the BMW Colour System for factory-quality refinishing. Hydracure technology ensures efficient water-based curing and Eco+ energy-saving mode reduces operational costs. The entire installation was completed while the bodyshop remained fully operational throughout.',
    testimonial_quote: 'You\'ve done an amazing job! The booths are fantastic, and the installation couldn\'t have gone smoother. We changed paint schemes and underwent training, all while staying operational.',
    testimonial_author: 'Reuben Abbott, Bodyshop Manager — Sandal BMW',
  },
  'smallest-cog': {
    slug: 'smallest-cog',
    title: 'The Smallest COG — Richard Hammond\'s Workshop',
    client_name: 'The Smallest Cog',
    sector: 'Automotive',
    cover_image_url: '/media/projects/smallest-cog/hero.jpg',
    gallery_images: [
      '/media/projects/smallest-cog/hero.jpg',
      '/media/projects/smallest-cog/gallery-1.jpg',
      '/media/projects/smallest-cog/gallery-2.jpg',
      '/media/projects/smallest-cog/gallery-3.png',
      '/media/projects/smallest-cog/gallery-4.png',
      '/media/projects/smallest-cog/gallery-5.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Automotive' },
      { label: 'Date', value: 'March 2024' },
      { label: 'Equipment', value: 'Poseidon + Hades + PMR' },
      { label: 'Location', value: 'Cotswolds, UK' },
    ],
    brief: 'The Smallest COG, owned by presenter Richard Hammond, is a Cotswolds workshop dedicated to restoring and refinishing iconic vehicles with exceptional precision. The project required a compact but fully professional refinishing setup — demonstrating that even in space-constrained environments, uncompromising quality is achievable.',
    solution: 'Todd Engineering delivered a Poseidon Spray Booth with full downdraught extraction and Eco+ energy-saving modes for flawless restoration finishes, a Hades Preparation Room with advanced airflow and extraction seamlessly connected to the booth, a Paint Mixing Room for accurate colour matching essential for high-value classic and luxury vehicle restorations, and a high-performance Compressor System providing reliable air supply across all refinishing processes.',
  },
  'hills-helicopters': {
    slug: 'hills-helicopters',
    title: 'Hills Helicopters — HX50 Production Facility',
    client_name: 'Hills Helicopters',
    sector: 'Aerospace',
    cover_image_url: '/media/projects/hills-helicopters/hero.jpg',
    gallery_images: [
      '/media/projects/hills-helicopters/hero.jpg',
      '/media/projects/hills-helicopters/gallery-1.jpg',
      '/media/projects/hills-helicopters/gallery-2.jpg',
      '/media/projects/hills-helicopters/gallery-3.jpg',
      '/media/projects/hills-helicopters/gallery-4.jpg',
      '/media/projects/hills-helicopters/gallery-5.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Aerospace' },
      { label: 'Date', value: 'October 2024' },
      { label: 'Equipment', value: 'Poseidon + PMR + Composite Rooms' },
      { label: 'Vehicle', value: 'HX50 Helicopter' },
    ],
    brief: 'Hills Helicopters, a leader in bespoke helicopter design and manufacturing, required a highly specialised finishing facility for production of the HX50 helicopter. The project demanded spray booth technology and bespoke composite manufacturing environments built to aerospace specification — where environmental control is critical to structural integrity.',
    solution: 'Todd Engineering delivered a Poseidon Spray Booth with raised floor for optimised airflow and full downdraught extraction, a dedicated Paint Mixing Room integrated into the booth workflow, and temperature-controlled Composite Rooms maintaining strict environmental conditions to preserve the integrity of composite materials critical to HX50 production. An existing Todd Engineering oven was also relocated to the new facility, ensuring workflow continuity from day one.',
    testimonial_quote: 'The installations from Todd Engineering have been instrumental in bringing our new facility to life. The Poseidon spray booth and composite rooms are essential to our operations. Todd Engineering\'s expertise and attention to detail have exceeded our expectations.',
    testimonial_author: 'Mark, Production Director — Hills Helicopters',
  },
  'sail-gp': {
    slug: 'sail-gp',
    title: 'Sail GP — Zeus All-Electric Spray Booth',
    client_name: 'Sail GP',
    sector: 'Marine',
    cover_image_url: '/media/projects/sail-gp/hero.jpg',
    gallery_images: [
      '/media/projects/sail-gp/hero.jpg',
      '/media/projects/sail-gp/gallery-1.jpg',
      '/media/projects/sail-gp/gallery-2.jpg',
      '/media/projects/sail-gp/gallery-3.jpg',
      '/media/projects/sail-gp/gallery-4.jpg',
      '/media/projects/sail-gp/gallery-5.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Marine / Sport' },
      { label: 'Date', value: 'September 2024' },
      { label: 'Energy', value: '100% Renewable' },
      { label: 'Type', value: 'Carbon-Neutral Installation' },
    ],
    brief: 'Todd Engineering installed a bespoke Zeus all-electric commercial spray booth at Sail GP — the world\'s most exciting sailing championship. The booth was specifically tailored to meet the unique demands of Sail GP\'s operations, running entirely on renewable energy as a central part of their carbon-neutral operational strategy.',
    solution: 'The Zeus All-Electric Drive-Through Booth was specifically engineered for Sail GP\'s high-performance vessels, with a drive-through design allowing seamless operations with minimal turnaround downtime. Far Infrared Curing Technology penetrates at molecular level for efficient curing while maintaining lower part temperatures — crucial for performance composite materials. Side extraction provides optimal airflow and high & low-level lighting delivers full visibility for precision inspection and application.',
  },
  'wfel': {
    slug: 'wfel',
    title: 'WFEL — Boxer Armoured Vehicle Facility',
    client_name: 'WFEL',
    sector: 'Defence',
    cover_image_url: '/media/projects/wfel/hero.jpg',
    gallery_images: [
      '/media/projects/wfel/hero.jpg',
      '/media/projects/wfel/gallery-1.jpg',
      '/media/projects/wfel/gallery-2.jpg',
      '/media/projects/wfel/gallery-3.jpg',
      '/media/projects/wfel/gallery-4.jpg',
      '/media/projects/wfel/gallery-5.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Defence' },
      { label: 'Date', value: 'August 2024' },
      { label: 'Equipment', value: 'Titan CV (26m) + Inspection Pit' },
      { label: 'Vehicle', value: 'Boxer Armoured Vehicles' },
    ],
    brief: 'WFEL, a global leader in defence manufacturing and producer of the iconic Boxer Armoured Vehicles, required a purpose-built refinishing solution to enhance their manufacturing capabilities. The project demanded the highest standards of precision, durability and compliance with military-grade coating specifications.',
    solution: 'Todd Engineering delivered a Titan CV Spray Booth — 26 metres long, two-stage drive-through design specifically for large-scale military vehicles — with full downdraught extraction for a pristine working environment. High, mid and low-level lighting ensures flawless application across the entire vehicle surface. A centralised Inspection Pit integrated with comprehensive extraction systems enables safe under-vehicle inspection to military-grade standards. The installation includes a dedicated Paint Mixing Room and a plant room housing an ABAC air compressor and WORKY dust extraction system.',
    testimonial_quote: 'The seamless integration of the Titan CV spray booth into our production line has significantly improved our throughput while maintaining the high standards essential for defence manufacturing.',
    testimonial_author: 'WFEL Team',
  },
  'gemini-taunton': {
    slug: 'gemini-taunton',
    title: 'Gemini Taunton — Turnkey Installation',
    client_name: 'Gemini Taunton',
    sector: 'Automotive',
    cover_image_url: '/media/projects/gemini-taunton/hero.jpg',
    gallery_images: [
      '/media/projects/gemini-taunton/hero.jpg',
      '/media/projects/gemini-taunton/gallery-1.jpg',
      '/media/projects/gemini-taunton/gallery-2.jpg',
      '/media/projects/gemini-taunton/gallery-3.jpg',
      '/media/projects/gemini-taunton/gallery-4.jpg',
      '/media/projects/gemini-taunton/gallery-5.jpg',
      '/media/projects/gemini-taunton/gallery-6.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Automotive' },
      { label: 'Date', value: 'April 2025' },
      { label: 'Equipment', value: 'Zeus All-Electric + Track & Skate' },
      { label: 'Location', value: 'Taunton, UK' },
    ],
    brief: 'Todd Engineering delivered a comprehensive turnkey installation for Gemini Taunton, a long-standing customer. A temporary booth was installed to maintain full operational continuity while the new Zeus all-electric system was commissioned — demonstrating Todd Engineering\'s commitment to zero-downtime delivery.',
    solution: 'The installation centred on a Zeus All-Electric Spray Booth with far infrared curing technology, side-loading roller shutter door and all-electric operation aligned with carbon-neutral goals. A Track & Skate System enables seamless vehicle movement from preparation through to the refinishing stage, significantly improving workflow. A dedicated Paint Mixing Room is positioned adjacent to the spray booth for optimal efficiency. A temporary Olympian Booth was installed during the transition period to maintain zero operational downtime throughout the project.',
    testimonial_quote: 'Everything went and was fine yesterday, thank you. I would like to commend every one of you involved in the installation. From your good self to the guys who have been working so hard to complete the install. Please pass on my thanks!',
    testimonial_author: 'Stuart, General Manager — Gemini Taunton',
  },
  'al-haddad-motors': {
    slug: 'al-haddad-motors',
    title: 'Al Haddad Motors — Mercedes-Benz Bahrain',
    client_name: 'Al Haddad Motors',
    sector: 'Export / Automotive',
    cover_image_url: '/media/projects/al-haddad-motors/hero.jpg',
    gallery_images: [
      '/media/projects/al-haddad-motors/hero.jpg',
      '/media/projects/al-haddad-motors/gallery-1.jpg',
      '/media/projects/al-haddad-motors/gallery-2.jpg',
      '/media/projects/al-haddad-motors/gallery-3.jpg',
      '/media/projects/al-haddad-motors/gallery-4.jpg',
      '/media/projects/al-haddad-motors/gallery-5.jpg',
      '/media/projects/al-haddad-motors/gallery-6.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Export / Automotive' },
      { label: 'Date', value: 'February 2025' },
      { label: 'Equipment', value: 'Zeus + Curing Oven + Twin Hades' },
      { label: 'Location', value: 'Bahrain' },
    ],
    brief: 'Al Haddad Motors, the official Mercedes-Benz dealer in Bahrain with over 60 years of automotive excellence, required a full turnkey refinishing solution meeting the exacting standards of the Mercedes-Benz refinishing programme. Every aspect of the facility was engineered to maximise workflow efficiency and precision.',
    solution: 'Todd Engineering delivered a Zeus All-Electric Spray Booth with advanced far infrared curing technology for fast drying times and exceptional energy efficiency. A Curing Oven with roller shutter door was positioned side-by-side with the spray booth for seamless transition between painting and curing phases. A Track & Skate System enables effortless vehicle movement between refinishing stages, minimising manual handling. Twin Hades Preparation Booths positioned opposite the spray booth and oven provide dust-free sanding, priming and masking before painting — the entire facility designed, planned, installed and commissioned end-to-end by Todd Engineering.',
    testimonial_quote: 'Everything is great our end — the lads have been a credit to your company. Please pass on my thanks to each of them.',
    testimonial_author: 'Darren, Group Aftersales Manager — Al Haddad Motors',
  },
  'angus-mackinnon': {
    slug: 'angus-mackinnon',
    title: 'Angus MacKinnon — Carbon-Neutral Bodyshop',
    client_name: 'Angus MacKinnon',
    sector: 'Automotive',
    cover_image_url: '/media/projects/angus-mackinnon/hero.png',
    gallery_images: [
      '/media/projects/angus-mackinnon/hero.png',
      '/media/projects/angus-mackinnon/gallery-1.png',
      '/media/projects/angus-mackinnon/gallery-2.png',
      '/media/projects/angus-mackinnon/gallery-3.png',
      '/media/projects/angus-mackinnon/gallery-4.png',
      '/media/projects/angus-mackinnon/gallery-5.png',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Automotive' },
      { label: 'Date', value: 'November 2024' },
      { label: 'Equipment', value: '2× Zeus All-Electric + PMR' },
      { label: 'Location', value: 'Uttoxeter, UK' },
    ],
    brief: 'Angus MacKinnon, a valued Todd Engineering customer for over two years, opened a purpose-built bodyshop in Uttoxeter with sustainability at the core of every decision. After witnessing the Zeus all-electric system in action at a neighbouring facility, owner Stuart committed to an all-electric setup with solar integration planned — setting a benchmark for the sector.',
    solution: 'Todd Engineering installed two Zeus Full Downdraught Spray Booths with all-electric operation eliminating fossil fuels entirely, raised floor design for optimised airflow and superior finish quality. Far Infrared Curing Technology cures paint at molecular level for faster drying times and measurably lower energy consumption. A Paint Mixing Room provides advanced controls for seamless workflow and precise colour matching, supported by a high-performance Compressor System. The facility has been designed to integrate solar energy in the future, targeting fully renewable-powered operation.',
  },
  'rhodes': {
    slug: 'rhodes',
    title: 'Rhodes — Carbon-Neutral Facility',
    client_name: 'Rhodes Accident Repair Centre',
    sector: 'Automotive',
    cover_image_url: '/media/projects/rhodes/hero.jpg',
    gallery_images: [
      '/media/projects/rhodes/hero.jpg',
      '/media/projects/rhodes/gallery-1.jpg',
      '/media/projects/rhodes/gallery-2.jpg',
      '/media/projects/rhodes/gallery-3.jpg',
      '/media/projects/rhodes/gallery-4.jpg',
      '/media/projects/rhodes/gallery-5.jpg',
      '/media/projects/rhodes/gallery-6.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Automotive' },
      { label: 'Date', value: 'November 2024' },
      { label: 'Equipment', value: 'Zeus + 2× Hades + PMR' },
      { label: 'Energy', value: 'All-Electric + Solar' },
    ],
    brief: 'Rhodes Accident Repair Centre in Rugeley has been a long-standing Todd Engineering customer. Their new purpose-built facility was designed from the ground up to achieve carbon neutrality — combining an all-electric Todd Engineering setup with solar battery storage to minimise grid reliance and demonstrate what the future of bodyshop operations looks like.',
    solution: 'Todd Engineering installed a Zeus Spray Booth centrally positioned with twin-loading roller shutter doors for enhanced access and operational flexibility, two Hades Preparation Booths with advanced airflow and extraction for clean, efficient vehicle preparation, and a Paint Mixing Room with centralised controls ensuring precise colour matching. A high-performance Compressor System supports all operational processes, complemented by Solar Battery Storage reducing grid reliance and supporting the facility\'s carbon-neutral ambitions.',
    testimonial_quote: 'The new facility has exceeded our expectations. Todd Engineering\'s expertise and top-quality equipment have been pivotal in creating a carbon-neutral setup that meets our operational needs while supporting our sustainability goals.',
    testimonial_author: 'Freddie, Bodyshop Manager — Rhodes Accident Repair Centre',
  },
  'rmd-kwikform': {
    slug: 'rmd-kwikform',
    title: 'RMD Kwikform — Titan CV Installation',
    client_name: 'RMD Kwikform',
    sector: 'Industrial',
    cover_image_url: '/media/projects/rmd-kwikform/hero.jpg',
    gallery_images: [
      '/media/projects/rmd-kwikform/hero.jpg',
      '/media/projects/rmd-kwikform/gallery-1.jpg',
      '/media/projects/rmd-kwikform/gallery-2.jpg',
      '/media/projects/rmd-kwikform/gallery-3.jpg',
      '/media/projects/rmd-kwikform/gallery-4.jpg',
      '/media/projects/rmd-kwikform/gallery-5.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Industrial' },
      { label: 'Date', value: 'February 2025' },
      { label: 'Equipment', value: 'Titan CV Drive-Through' },
      { label: 'Features', value: 'BAXT Wall Protection + Training' },
    ],
    brief: 'RMD Kwikform, a global leader in formwork, falsework and ground shoring solutions, required a high-performance, purpose-built spray booth to meet their exacting industrial refinishing standards. Todd Engineering delivered a Titan CV drive-through system with BAXT wall protection and a dedicated operator training programme.',
    solution: 'The Titan CV Drive-Through Spray Booth was customised for industrial workflow, enabling vehicles and equipment to pass through without interruption. A side extraction system maintains superior airflow and a clean working environment. High and low-level LED lighting ensures optimal visibility across all surfaces. BAXT 5-Layer Wall Protection — self-adhesive peel-away layers — extends booth lifespan and reduces maintenance downtime. The installation included a dedicated hands-on Operator Training programme covering operation, safety protocols and maintenance best practices.',
  },
  'hgv-solutions': {
    slug: 'hgv-solutions',
    title: 'HGV Solutions — Zeus Commercial Booth',
    client_name: 'HGV Solutions',
    sector: 'Industrial',
    cover_image_url: '/media/projects/hgv-solutions/hero.png',
    gallery_images: [
      '/media/projects/hgv-solutions/hero.png',
      '/media/projects/hgv-solutions/gallery-1.jpg',
      '/media/projects/hgv-solutions/gallery-2.jpg',
      '/media/projects/hgv-solutions/gallery-3.jpg',
      '/media/projects/hgv-solutions/gallery-4.jpg',
      '/media/projects/hgv-solutions/gallery-5.jpg',
      '/media/projects/hgv-solutions/gallery-6.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Industrial / Commercial' },
      { label: 'Date', value: 'November 2024' },
      { label: 'Equipment', value: 'Zeus Commercial (32m × 5.5m × 6.5m)' },
      { label: 'Energy', value: 'All-Electric' },
    ],
    brief: 'HGV Solutions has been at the forefront of sustainable refinishing adoption, transitioning from gas-fired booths to Zeus all-electric systems since 2022. This installation of the first Zeus Commercial Spray Booth — purpose-built for large commercial vehicles — marks the latest chapter in an ongoing partnership with Todd Engineering.',
    solution: 'Todd Engineering delivered a Zeus Commercial Spray Booth at 32m long × 5.5m wide × 6.5m high, specifically engineered for large commercial vehicles with all-electric operation. Far Infrared (FIR) Technology provides molecular-level paint curing, faster drying times and lower panel temperatures ideal for commercial vehicle surfaces. Eco+ Energy Saving Modes deliver automated energy management reducing operational costs while maintaining peak performance — all custom-engineered to HGV Solutions\' exact site and workflow requirements.',
  },
  'autolux': {
    slug: 'autolux',
    title: 'Autolux Body & Paint — All-Electric Nemesis Setup',
    client_name: 'Autolux Body & Paint',
    sector: 'Automotive',
    cover_image_url: '/media/projects/autolux/hero.jpg',
    gallery_images: [
      '/media/projects/autolux/hero.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Automotive' },
      { label: 'Date', value: 'October 2024' },
      { label: 'Equipment', value: '2× Zeus + 2× Hades + PMR' },
      { label: 'Type', value: 'All-Electric Nemesis Setup' },
    ],
    brief: 'Autolux Body & Paint, a premier accident repair centre committed to high-quality repairs and environmental responsibility, partnered with Todd Engineering to install a state-of-the-art all-electric Nemesis setup. The comprehensive solution dramatically improved workflow efficiency and sustainability performance across the facility.',
    solution: 'Todd Engineering delivered two Zeus All-Electric Spray Booths with far infrared technology for energy-efficient curing and faster turnaround times, eliminating fossil fuel use entirely. Two Hades Preparation Booths with superior air extraction systems provide clean, efficient vehicle preparation with smooth transitions to the spray stage. A fully equipped Paint Mixing Room ensures optimal colour accuracy and precision matching, supported by a high-performance Compressor System and a Plant Room housing all critical equipment with additional operational storage.',
  },
  'jet-glow': {
    slug: 'jet-glow',
    title: 'Jet Glow — Integrated Refinishing Solution',
    client_name: 'Jet Glow',
    sector: 'Automotive',
    cover_image_url: '/media/projects/jet-glow/hero.jpg',
    gallery_images: [
      '/media/projects/jet-glow/hero.jpg',
      '/media/projects/jet-glow/gallery-1.jpg',
      '/media/projects/jet-glow/gallery-2.jpg',
      '/media/projects/jet-glow/gallery-3.jpg',
      '/media/projects/jet-glow/gallery-4.jpg',
      '/media/projects/jet-glow/gallery-5.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Automotive' },
      { label: 'Date', value: 'October 2024' },
      { label: 'Equipment', value: '2× Zeus Prep + Titan + PMR' },
      { label: 'Type', value: 'Integrated Multi-Booth System' },
    ],
    brief: 'Jet Glow approached Todd Engineering to upgrade their facilities with a tailored solution aimed at optimising workflow and boosting throughput. Todd Engineering designed and installed a fully integrated multi-booth system where roller shutter doors connect each stage — creating a seamless, uninterrupted path from preparation through to final finish.',
    solution: 'Two Zeus Preparation Booths — electrically heated for consistent, efficient preparation — are designed to support high-volume operations with built-in energy efficiency. A Titan Spray Booth provides robust performance and precision delivery, fully integrated into the sequential workflow. A Roller Shutter Connection System links all three booths for effortless vehicle movement between stages, minimising downtime between preparation and spraying. WORKY Dust Extraction is flush-mounted within preparation booth walls for a clean working environment and improved finish quality. A strategically placed Paint Mixing Room enables easy access and precise colour preparation.',
    testimonial_quote: 'Since the installation, we\'ve seen significant improvements in our operational flow and productivity. The innovative setup underscores our commitment to advanced technology and maintaining excellence in refinishing standards.',
    testimonial_author: 'Jet Glow Team',
  },
  'mg-accident-repair': {
    slug: 'mg-accident-repair',
    title: 'MG Accident Repair Centre — Zeus Upgrade',
    client_name: 'MG Accident Repair Centre',
    sector: 'Automotive',
    cover_image_url: '/media/projects/mg-accident-repair/hero.png',
    gallery_images: [
      '/media/projects/mg-accident-repair/hero.png',
      '/media/projects/mg-accident-repair/gallery-1.jpg',
      '/media/projects/mg-accident-repair/gallery-2.jpg',
      '/media/projects/mg-accident-repair/gallery-3.jpg',
      '/media/projects/mg-accident-repair/gallery-4.jpg',
      '/media/projects/mg-accident-repair/gallery-5.jpg',
    ],
    outcome_stats: [
      { label: 'Sector', value: 'Automotive' },
      { label: 'Date', value: 'July 2024' },
      { label: 'Result', value: '50% productivity increase' },
      { label: 'Type', value: 'Carbon-Neutral Upgrade' },
    ],
    brief: 'MG Accident Repair Centre, a long-standing Todd Engineering customer, upgraded from their existing Spartan booth to the Zeus all-electric system — driven by carbon-neutral goals, PAS 2060 compliance ambitions and the desire to reclaim space previously occupied by a gas bulk tank. The results exceeded expectations across every metric.',
    solution: 'Todd Engineering installed the Zeus All-Electric Spray Booth adjacent to the existing Spartan booth following successful operational trials. Elimination of the gas bulk tank reclaimed significant floor space and removed ongoing fuel supply costs. All-electric operation directly supports MG\'s carbon-neutral certification journey toward PAS 2060 compliance. Far infrared technology delivers faster cycle times — with a 50% increase in productivity reported following the transition to the Zeus system.',
  },
}

export const PROJECTS_LIST = Object.values(PROJECTS_DATA)
